# Generated by Django 5.2.11 on 2026-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0002_alter_ecgrecord_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='lime_explanation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='lime_image',
            field=models.ImageField(blank=True, null=True, upload_to='lime_explanations/%Y/%m/%d/'),
        ),
    ]
