# Generated by Django 5.2.11 on 2026-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0003_ecgrecord_lime_explanation_data_ecgrecord_lime_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgrecord',
            name='lime_image',
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
