# Generated by Django 5.2.11 on 2026-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0005_patient_ecgrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional: Email address to send reports to.', max_length=254),
        ),
    ]
