# Generated by Django 5.2.11 on 2026-03-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0006_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('clinic', 'Clinic / Organization')], default='user', max_length=20),
        ),
    ]
